---@meta

---@alias PaneDirection
---|"Down"
---|"Left"
---|"Next"
---|"Prev"
---|"Right"
---|"Up"

---@class MuxSize
---@field rows number
---@field cols number
---@field pixel_width number
---@field pixel_height number
---@field dpi number

---@class PaneInfo
---@field index number
---@field is_active bool
---@field is_zoomed bool
---@field left number
---@field top number
---@field width number
---@field height number
---@field pixel_width number
---@field pixel_height number
---@field pane Pane

-- `MuxTabObj` represents a tab that is managed by the multiplexer
---@class MuxTabObj
-- Activates (focuses) the tab
---@field activate fun(self: MuxTabObj): nil
-- A convenience accessor for returning the active pane in the tab
---@field active_pane fun(self): Pane
-- Returns pane adjacent to the active pane in tab in the direction direction
---@field get_pane_direction fun(self: MuxTabObj, direction: PaneDirection): MuxTabObj
-- Returns the overall size of the tab,
-- taking into account all of the contained panes
---@field get_size fun(self: MuxTabObj): MuxSize
-- Returns the tab title as set by `tab:set_title()`
---@field get_title fun(self: MuxTabObj): string
-- Returns an array table containing the set of Pane objects contained by this tab
---@field panes fun(self: MuxTabObj): Pane[]
-- Returns an array table containing an extended info entry for each of the panes contained by this tab
---@field panes_with_info fun(self: MuxTabObj): PaneInfo[]
-- Rotates the panes in the clockwise direction
---@field rotate_clockwise fun(self: MuxTabObj): nil
-- Rotates the panes in the counter-clockwise direction
---@field rotate_counter_clockwise fun(self: MuxTabObj): nil
-- Sets the tab title to the provided string
---@field set_title fun(self: MuxTabObj, title: string): nil
-- Sets the zoomed state for the active pane within this tab.
-- A zoomed pane takes up all available space in the tab,
-- hiding all other panes while it is zoomed.
-- Switching its zoom state off will restore the prior split arrangement.
-- Setting the zoom state to true zooms the pane if it wasn't already zoomed.
-- Setting the zoom state to false un-zooms the pane if it was zoomed.
-- Returns the prior zoom state
---@field set_zoomed fun(self: MuxTabObj, state: bool): bool
-- Returns the tab id
---@field tab_id fun(self: MuxTabObj): number
-- Returns the MuxWindow object that contains this tab
---@field window fun(self: MuxTabObj): MuxWindow
