---@meta

-- TODO: Make key and mods more specific

---@alias KeyAssignment
---|"ActivateCommandPalette"
---|"ActivateCopyMode"
---|"ActivateKeyTable"
---|"ActivateLastTab"
---|"ActivatePaneByIndex"
---|"ActivatePaneDirection"
---|"ActivateTab"
---|"ActivateTabRelative"
---|"ActivateTabRelativeNoWrap"
---|"ActivateWindow"
---|"ActivateWindowRelative"
---|"ActivateWindowRelativeNoWrap"
---|"AdjustPaneSize"
---|"AttachDomain"
---|"CharSelect"
---|"ClearKeyTableStack"
---|"ClearScrollback"
---|"ClearSelection"
---|"CloseCurrentPane"
---|"CloseCurrentTab"
---|"CompleteSelection"
---|"CompleteSelectionOrOpenLinkAtMouseCursor"
---|"Copy"
---|"CopyTo"
---|"DecreaseFontSize"
---|"DetachDomain"
---|"DisableDefaultAssignment"
---|"EmitEvent"
---|"ExtendSelectionToMouseCursor"
---|"Hide"
---|"HideApplication"
---|"IncreaseFontSize"
---|"InputSelector"
---|"MoveTab"
---|"MoveTabRelative"
---|"Multiple"
---|"Nop"
---|"OpenLinkAtMouseCursor"
---|"PaneSelect"
---|"Paste"
---|"PasteFrom"
---|"PastePrimarySelection"
---|"PopKeyTable"
---|"PromptInputLine"
---|"QuickSelect"
---|"QuickSelectArgs"
---|"QuitApplication"
---|"ReloadConfiguration"
---|"ResetFontAndWindowSize"
---|"ResetFontSize"
---|"ResetTerminal"
---|"RotatePanes"
---|"ScrollByCurrentEventWheelDelta"
---|"ScrollByLine"
---|"ScrollByPage"
---|"ScrollToBottom"
---|"ScrollToPrompt"
---|"ScrollToTop"
---|"Search"
---|"SelectTextAtMouseCursor"
---|"SendKey"
---|"SendString"
---|"SetPaneZoomState"
---|"Show"
---|"ShowDebugOverlay"
---|"ShowLauncher"
---|"ShowLauncherArgs"
---|"ShowTabNavigator"
---|"SpawnCommandInNewTab"
---|"SpawnCommandInNewWindow"
---|"SpawnTab"
---|"SpawnWindow"
---|"SplitHorizontal"
---|"SplitPane"
---|"SplitVertical"
---|"StartWindowDrag"
---|"SwitchToWorkspace"
---|"SwitchWorkspaceRelative"
---|"ToggleFullScreen"
---|"TogglePaneZoomState"

---@class KeyNoAction
---@field key string
---@field mods? string

---@class Key :KeyNoAction
---@field action KeyAssignment

---@alias KeyAssignFunction fun(param: any): KeyAssignment

-- Can also be called as function like older versions of wezterm did
---@class ActionFuncClass
---@field ActivateCommandPalette KeyAssignFunction
---@field ActivateCopyMode KeyAssignFunction
---@field ActivateKeyTable KeyAssignFunction
---@field ActivateLastTab KeyAssignFunction
---@field ActivatePaneByIndex KeyAssignFunction
---@field ActivatePaneDirection KeyAssignFunction
---@field ActivateTab KeyAssignFunction
---@field ActivateTabRelative KeyAssignFunction
---@field ActivateTabRelativeNoWrap KeyAssignFunction
---@field ActivateWindow KeyAssignFunction
---@field ActivateWindowRelative KeyAssignFunction
---@field ActivateWindowRelativeNoWrap KeyAssignFunction
---@field AdjustPaneSize KeyAssignFunction
---@field AttachDomain KeyAssignFunction
---@field CharSelect KeyAssignFunction
---@field ClearKeyTableStack KeyAssignFunction
---@field ClearScrollback KeyAssignFunction
---@field ClearSelection KeyAssignFunction
---@field CloseCurrentPane KeyAssignFunction
---@field CloseCurrentTab KeyAssignFunction
---@field CompleteSelection KeyAssignFunction
---@field CompleteSelectionOrOpenLinkAtMouseCursor KeyAssignFunction
---@field Copy KeyAssignFunction
---@field CopyTo KeyAssignFunction
---@field DecreaseFontSize KeyAssignFunction
---@field DetachDomain KeyAssignFunction
---@field DisableDefaultAssignment KeyAssignFunction
---@field EmitEvent KeyAssignFunction
---@field ExtendSelectionToMouseCursor KeyAssignFunction
---@field Hide KeyAssignFunction
---@field HideApplication KeyAssignFunction
---@field IncreaseFontSize KeyAssignFunction
---@field InputSelector KeyAssignFunction
---@field MoveTab KeyAssignFunction
---@field MoveTabRelative KeyAssignFunction
---@field Multiple KeyAssignFunction
---@field Nop KeyAssignFunction
---@field OpenLinkAtMouseCursor KeyAssignFunction
---@field PaneSelect KeyAssignFunction
---@field Paste KeyAssignFunction
---@field PasteFrom KeyAssignFunction
---@field PastePrimarySelection KeyAssignFunction
---@field PopKeyTable KeyAssignFunction
---@field PromptInputLine KeyAssignFunction
---@field QuickSelect KeyAssignFunction
---@field QuickSelectArgs KeyAssignFunction
---@field QuitApplication KeyAssignFunction
---@field ReloadConfiguration KeyAssignFunction
---@field ResetFontAndWindowSize KeyAssignFunction
---@field ResetFontSize KeyAssignFunction
---@field ResetTerminal KeyAssignFunction
---@field RotatePanes KeyAssignFunction
---@field ScrollByCurrentEventWheelDelta KeyAssignFunction
---@field ScrollByLine KeyAssignFunction
---@field ScrollByPage KeyAssignFunction
---@field ScrollToBottom KeyAssignFunction
---@field ScrollToPrompt KeyAssignFunction
---@field ScrollToTop KeyAssignFunction
---@field Search KeyAssignFunction
---@field SelectTextAtMouseCursor KeyAssignFunction
---@field SendKey KeyAssignFunction
---@field SendString KeyAssignFunction
---@field SetPaneZoomState KeyAssignFunction
---@field Show KeyAssignFunction
---@field ShowDebugOverlay KeyAssignFunction
---@field ShowLauncher KeyAssignFunction
---@field ShowLauncherArgs KeyAssignFunction
---@field ShowTabNavigator KeyAssignFunction
---@field SpawnCommandInNewTab KeyAssignFunction
---@field SpawnCommandInNewWindow KeyAssignFunction
---@field SpawnTab KeyAssignFunction
---@field SpawnWindow KeyAssignFunction
---@field SplitHorizontal KeyAssignFunction
---@field SplitPane KeyAssignFunction
---@field SplitVertical KeyAssignFunction
---@field StartWindowDrag KeyAssignFunction
---@field SwitchToWorkspace KeyAssignFunction
---@field SwitchWorkspaceRelative KeyAssignFunction
---@field ToggleFullScreen KeyAssignFunction
---@field TogglePaneZoomState KeyAssignFunction

---@class ActionClass
---@field ActivateCommandPalette any
---@field ActivateCopyMode any
---@field ActivateKeyTable any
---@field ActivateLastTab any
---@field ActivatePaneByIndex any
---@field ActivatePaneDirection any
---@field ActivateTab any
---@field ActivateTabRelative any
---@field ActivateTabRelativeNoWrap any
---@field ActivateWindow any
---@field ActivateWindowRelative any
---@field ActivateWindowRelativeNoWrap any
---@field AdjustPaneSize any
---@field AttachDomain any
---@field CharSelect any
---@field ClearKeyTableStack any
---@field ClearScrollback any
---@field ClearSelection any
---@field CloseCurrentPane any
---@field CloseCurrentTab any
---@field CompleteSelection any
---@field CompleteSelectionOrOpenLinkAtMouseCursor any
---@field Copy any
---@field CopyTo any
---@field DecreaseFontSize any
---@field DetachDomain any
---@field DisableDefaultAssignment any
---@field EmitEvent any
---@field ExtendSelectionToMouseCursor any
---@field Hide any
---@field HideApplication any
---@field IncreaseFontSize any
---@field InputSelector any
---@field MoveTab any
---@field MoveTabRelative any
---@field Multiple any
---@field Nop any
---@field OpenLinkAtMouseCursor any
---@field PaneSelect any
---@field Paste any
---@field PasteFrom any
---@field PastePrimarySelection any
---@field PopKeyTable any
---@field PromptInputLine any
---@field QuickSelect any
---@field QuickSelectArgs any
---@field QuitApplication any
---@field ReloadConfiguration any
---@field ResetFontAndWindowSize any
---@field ResetFontSize any
---@field ResetTerminal any
---@field RotatePanes any
---@field ScrollByCurrentEventWheelDelta any
---@field ScrollByLine any
---@field ScrollByPage any
---@field ScrollToBottom any
---@field ScrollToPrompt any
---@field ScrollToTop any
---@field Search any
---@field SelectTextAtMouseCursor any
---@field SendKey any
---@field SendString any
---@field SetPaneZoomState any
---@field Show any
---@field ShowDebugOverlay any
---@field ShowLauncher any
---@field ShowLauncherArgs any
---@field ShowTabNavigator any
---@field SpawnCommandInNewTab any
---@field SpawnCommandInNewWindow any
---@field SpawnTab any
---@field SpawnWindow any
---@field SplitHorizontal any
---@field SplitPane any
---@field SplitVertical any
---@field StartWindowDrag any
---@field SwitchToWorkspace any
---@field SwitchWorkspaceRelative any
---@field ToggleFullScreen any
---@field TogglePaneZoomState any

-- Helper for defining key assignment actions in your configuration file.
-- This is really just sugar for the underlying Lua -> Rust deserialation mapping
-- that makes it a bit easier to identify where syntax errors may exist
-- in your configuration file
---@alias Action ActionFuncClass|fun(action: ActionClass)
