---@meta

-- TODO: Make key and mods more specific

---@alias KeyAssignment
---|"ActivateCommandPalette"
---|"ActivateCopyMode"
---|"ActivateKeyTable"
---|"ActivateLastTab"
---|"ActivatePaneByIndex"
---|"ActivatePaneDirection"
---|"ActivateTab"
---|"ActivateTabRelative"
---|"ActivateTabRelativeNoWrap"
---|"ActivateWindow"
---|"ActivateWindowRelative"
---|"ActivateWindowRelativeNoWrap"
---|"AdjustPaneSize"
---|"AttachDomain"
---|"CharSelect"
---|"ClearKeyTableStack"
---|"ClearScrollback"
---|"ClearSelection"
---|"CloseCurrentPane"
---|"CloseCurrentTab"
---|"CompleteSelection"
---|"CompleteSelectionOrOpenLinkAtMouseCursor"
---|"Copy"
---|"CopyTo"
---|"DecreaseFontSize"
---|"DetachDomain"
---|"DisableDefaultAssignment"
---|"EmitEvent"
---|"ExtendSelectionToMouseCursor"
---|"Hide"
---|"HideApplication"
---|"IncreaseFontSize"
---|"InputSelector"
---|"MoveTab"
---|"MoveTabRelative"
---|"Multiple"
---|"Nop"
---|"OpenLinkAtMouseCursor"
---|"PaneSelect"
---|"Paste"
---|"PasteFrom"
---|"PastePrimarySelection"
---|"PopKeyTable"
---|"PromptInputLine"
---|"QuickSelect"
---|"QuickSelectArgs"
---|"QuitApplication"
---|"ReloadConfiguration"
---|"ResetFontAndWindowSize"
---|"ResetFontSize"
---|"ResetTerminal"
---|"RotatePanes"
---|"ScrollByCurrentEventWheelDelta"
---|"ScrollByLine"
---|"ScrollByPage"
---|"ScrollToBottom"
---|"ScrollToPrompt"
---|"ScrollToTop"
---|"Search"
---|"SelectTextAtMouseCursor"
---|"SendKey"
---|"SendString"
---|"SetPaneZoomState"
---|"Show"
---|"ShowDebugOverlay"
---|"ShowLauncher"
---|"ShowLauncherArgs"
---|"ShowTabNavigator"
---|"SpawnCommandInNewTab"
---|"SpawnCommandInNewWindow"
---|"SpawnTab"
---|"SpawnWindow"
---|"SplitHorizontal"
---|"SplitPane"
---|"SplitVertical"
---|"StartWindowDrag"
---|"SwitchToWorkspace"
---|"SwitchWorkspaceRelative"
---|"ToggleFullScreen"
---|"TogglePaneZoomState"

---@class KeyNoAction
-- A single unicode character, like 'A' or 'a'. Pay attention to the case of the text that you use
-- and the state of the SHIFT modifier, as this matters whether 'A' or 'a' is matched.
--
-- Alternatively you can use on the following keycode identifiers, although note that not all of
-- these are meaningful on all platforms:
--
-- Hyper, Super, Meta, Cancel, Backspace, Tab, Clear, Enter, Shift, Escape, LeftShift, RightShift,
-- Control, LeftControl, RightControl, Alt, LeftAlt, RightAlt, Menu, LeftMenu, RightMenu, Pause,
-- CapsLock, VoidSymbol, PageUp, PageDown, End, Home, LeftArrow, RightArrow, UpArrow, DownArrow,
-- Select, Print, Execute, PrintScreen, Insert, Delete, Help, LeftWindows, RightWindows,
-- Applications, Sleep, Numpad0, Numpad1, Numpad2, Numpad3, Numpad4, Numpad5, Numpad6, Numpad7,
-- Numpad8, Numpad9, Multiply, Add, Separator, Subtract, Decimal, Divide, NumLock, ScrollLock,
-- BrowserBack, BrowserForward, BrowserRefresh, BrowserStop, BrowserSearch, BrowserFavorites,
-- BrowserHome, VolumeMute, VolumeDown, VolumeUp, MediaNextTrack, MediaPrevTrack, MediaStop,
-- MediaPlayPause, ApplicationLeftArrow, ApplicationRightArrow, ApplicationUpArrow,
-- ApplicationDownArrow, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17,
-- F18, F19, F20, F21, F22, F23, F24.
--
-- The key value can refer either to the physical position of a key on an ANSI US keyboard or to the
-- post-keyboard-layout-mapped value produced by a key press.
--
-- You can explicitly assign using the physical position by adding a phys: prefix to the value, for
-- example: `key="phys:A"`. This will match key presses for the key that would be in the position of
-- the A key on an ANSI US keyboard.
--
-- You can explicitly assign the mapped key by adding a mapped:
-- prefix to the value, for example: key="mapped:a" will match a
-- key press where the OS keyboard layout produces a, regardless of
-- its physical position.
--
-- If you omit an explicit prefix, wezterm will assume phys: and use the physical position of the
-- specified key.
--
-- The default key assignments listed above use `phys:`. In previous releases there was no physical
-- position support and those assignments were all `mapped:`.
--
-- When upgrading from earlier releases, if you had `{key="N", mods="CMD", ..}` in your config, you
-- will need to change it to either `{key="N", mods="CMD|SHIFT", ..}` or `{ key="mapped:N",
-- mods="CMD", ..}` in order to continue to respect the SHIFT modifier.
--
-- The `key_map_preference` option controls how keys without an explicit `phys:` or `mapped:` prefix
-- are treated. If `key_map_preference = "Mapped"` (the default), then `mapped:` is assumed. If
-- `key_map_preference = "Physical"` then `phys:` is assumed.
--
-- The default key assignments will respect `key_map_preference`.
--
-- In some cases, wezterm may not know how to represent a key event in either its phys: or mapped:
-- forms. In that case, you may wish to define an assignment in terms of the underlying operating
-- system key code, using a `raw: prefix`.
--
-- Similar in concept to the `phys:` mapping described above, the `raw:` mapping is independent of
-- the OS keyboard layout. Raw codes are hardware and windowing system dependent, so there is no
-- portable way to list which key does what.
--
-- To discover these values, you can set `debug_key_events = true` and press the keys of interest.
--
-- You can specify a raw key value of 123 by using `key="raw:123"` in your config rather than one of
-- the other key values.
--
---@field key string
-- Possible Modifier labels are:
--
-- `SUPER`, `CMD`, `WIN` - these are all equivalent: on macOS the Command key, on Windows the
-- Windows key, on Linux this can also be the Super or Hyper key. Left and right are equivalent.
--
-- `CTRL` - The control key. Left and right are equivalent.
--
-- `SHIFT` - The shift key. Left and right are equivalent.
--
-- `ALT`, `OPT`, `META` - these are all equivalent: on macOS the Option key, on other systems the
-- Alt or Meta key. Left and right are equivalent.
--
-- `LEADER` - a special modal modifier state managed by WezTerm.
--
-- `VoidSymbol` - This keycode is emitted in special cases where the original function of the key has
-- been removed. Such as in Linux and using setxkbmap: `setxkbmap -option caps:none`. The CapsLock
-- will no longer function as before in all applications, instead emitting `VoidSymbol`.

-- You can also combine modifiers using the `|` symbol, like `"CMD|CTRL"`.
--
---@field mods? string Optional modifiers keys.

---@class Key :KeyNoAction
---@field action KeyAssignment

-- Can also be called as function like older versions of wezterm did
---@class ActionFuncClass
---@field ActivateCommandPalette fun(param: any): KeyAssignment
---@field ActivateCopyMode fun(param: any): KeyAssignment
---@field ActivateKeyTable fun(param: any): KeyAssignment
---@field ActivateLastTab fun(param: any): KeyAssignment
---@field ActivatePaneByIndex fun(param: any): KeyAssignment
---@field ActivatePaneDirection fun(param: any): KeyAssignment
---@field ActivateTab fun(param: any): KeyAssignment
---@field ActivateTabRelative fun(param: any): KeyAssignment
---@field ActivateTabRelativeNoWrap fun(param: any): KeyAssignment
---@field ActivateWindow fun(param: any): KeyAssignment
---@field ActivateWindowRelative fun(param: any): KeyAssignment
---@field ActivateWindowRelativeNoWrap fun(param: any): KeyAssignment
---@field AdjustPaneSize fun(param: any): KeyAssignment
---@field AttachDomain fun(param: any): KeyAssignment
---@field CharSelect fun(param: any): KeyAssignment
---@field ClearKeyTableStack fun(param: any): KeyAssignment
---@field ClearScrollback fun(param: any): KeyAssignment
---@field ClearSelection fun(param: any): KeyAssignment
---@field CloseCurrentPane fun(param: any): KeyAssignment
---@field CloseCurrentTab fun(param: any): KeyAssignment
---@field CompleteSelection fun(param: any): KeyAssignment
---@field CompleteSelectionOrOpenLinkAtMouseCursor fun(param: any): KeyAssignment
---@field Copy fun(param: any): KeyAssignment
---@field CopyTo fun(param: any): KeyAssignment
---@field DecreaseFontSize fun(param: any): KeyAssignment
---@field DetachDomain fun(param: any): KeyAssignment
---@field DisableDefaultAssignment fun(param: any): KeyAssignment
---@field EmitEvent fun(param: any): KeyAssignment
---@field ExtendSelectionToMouseCursor fun(param: any): KeyAssignment
---@field Hide fun(param: any): KeyAssignment
---@field HideApplication fun(param: any): KeyAssignment
---@field IncreaseFontSize fun(param: any): KeyAssignment
---@field InputSelector fun(param: any): KeyAssignment
---@field MoveTab fun(param: any): KeyAssignment
---@field MoveTabRelative fun(param: any): KeyAssignment
---@field Multiple fun(param: any): KeyAssignment
---@field Nop fun(param: any): KeyAssignment
---@field OpenLinkAtMouseCursor fun(param: any): KeyAssignment
---@field PaneSelect fun(param: any): KeyAssignment
---@field Paste fun(param: any): KeyAssignment
---@field PasteFrom fun(param: any): KeyAssignment
---@field PastePrimarySelection fun(param: any): KeyAssignment
---@field PopKeyTable fun(param: any): KeyAssignment
---@field PromptInputLine fun(param: any): KeyAssignment
---@field QuickSelect fun(param: any): KeyAssignment
---@field QuickSelectArgs fun(param: any): KeyAssignment
---@field QuitApplication fun(param: any): KeyAssignment
---@field ReloadConfiguration fun(param: any): KeyAssignment
---@field ResetFontAndWindowSize fun(param: any): KeyAssignment
---@field ResetFontSize fun(param: any): KeyAssignment
---@field ResetTerminal fun(param: any): KeyAssignment
---@field RotatePanes fun(param: any): KeyAssignment
---@field ScrollByCurrentEventWheelDelta fun(param: any): KeyAssignment
---@field ScrollByLine fun(param: any): KeyAssignment
---@field ScrollByPage fun(param: any): KeyAssignment
---@field ScrollToBottom fun(param: any): KeyAssignment
---@field ScrollToPrompt fun(param: any): KeyAssignment
---@field ScrollToTop fun(param: any): KeyAssignment
---@field Search fun(param: any): KeyAssignment
---@field SelectTextAtMouseCursor fun(param: any): KeyAssignment
---@field SendKey fun(param: any): KeyAssignment
---@field SendString fun(param: any): KeyAssignment
---@field SetPaneZoomState fun(param: any): KeyAssignment
---@field Show fun(param: any): KeyAssignment
---@field ShowDebugOverlay fun(param: any): KeyAssignment
---@field ShowLauncher fun(param: any): KeyAssignment
---@field ShowLauncherArgs fun(param: any): KeyAssignment
---@field ShowTabNavigator fun(param: any): KeyAssignment
---@field SpawnCommandInNewTab fun(param: any): KeyAssignment
---@field SpawnCommandInNewWindow fun(param: any): KeyAssignment
---@field SpawnTab fun(param: any): KeyAssignment
---@field SpawnWindow fun(param: any): KeyAssignment
---@field SplitHorizontal fun(param: any): KeyAssignment
---@field SplitPane fun(param: any): KeyAssignment
---@field SplitVertical fun(param: any): KeyAssignment
---@field StartWindowDrag fun(param: any): KeyAssignment
---@field SwitchToWorkspace fun(param: any): KeyAssignment
---@field SwitchWorkspaceRelative fun(param: any): KeyAssignment
---@field ToggleFullScreen fun(param: any): KeyAssignment
---@field TogglePaneZoomState fun(param: any): KeyAssignment

---@class ActionClass
---@field ActivateCommandPalette any
---@field ActivateCopyMode any
---@field ActivateKeyTable any
---@field ActivateLastTab any
---@field ActivatePaneByIndex any
---@field ActivatePaneDirection any
---@field ActivateTab any
---@field ActivateTabRelative any
---@field ActivateTabRelativeNoWrap any
---@field ActivateWindow any
---@field ActivateWindowRelative any
---@field ActivateWindowRelativeNoWrap any
---@field AdjustPaneSize any
---@field AttachDomain any
---@field CharSelect any
---@field ClearKeyTableStack any
---@field ClearScrollback any
---@field ClearSelection any
---@field CloseCurrentPane any
---@field CloseCurrentTab any
---@field CompleteSelection any
---@field CompleteSelectionOrOpenLinkAtMouseCursor any
---@field Copy any
---@field CopyTo any
---@field DecreaseFontSize any
---@field DetachDomain any
---@field DisableDefaultAssignment any
---@field EmitEvent any
---@field ExtendSelectionToMouseCursor any
---@field Hide any
---@field HideApplication any
---@field IncreaseFontSize any
---@field InputSelector any
---@field MoveTab any
---@field MoveTabRelative any
---@field Multiple any
---@field Nop any
---@field OpenLinkAtMouseCursor any
---@field PaneSelect any
---@field Paste any
---@field PasteFrom any
---@field PastePrimarySelection any
---@field PopKeyTable any
---@field PromptInputLine any
---@field QuickSelect any
---@field QuickSelectArgs any
---@field QuitApplication any
---@field ReloadConfiguration any
---@field ResetFontAndWindowSize any
---@field ResetFontSize any
---@field ResetTerminal any
---@field RotatePanes any
---@field ScrollByCurrentEventWheelDelta any
---@field ScrollByLine any
---@field ScrollByPage any
---@field ScrollToBottom any
---@field ScrollToPrompt any
---@field ScrollToTop any
---@field Search any
---@field SelectTextAtMouseCursor any
---@field SendKey any
---@field SendString any
---@field SetPaneZoomState any
---@field Show any
---@field ShowDebugOverlay any
---@field ShowLauncher any
---@field ShowLauncherArgs any
---@field ShowTabNavigator any
---@field SpawnCommandInNewTab any
---@field SpawnCommandInNewWindow any
---@field SpawnTab any
---@field SpawnWindow any
---@field SplitHorizontal any
---@field SplitPane any
---@field SplitVertical any
---@field StartWindowDrag any
---@field SwitchToWorkspace any
---@field SwitchWorkspaceRelative any
---@field ToggleFullScreen any
---@field TogglePaneZoomState any

-- Helper for defining key assignment actions in your configuration file.
-- This is really just sugar for the underlying Lua -> Rust deserialation mapping
-- that makes it a bit easier to identify where syntax errors may exist
-- in your configuration file
---@alias Action ActionFuncClass|fun(action: ActionClass)
