name: Missing or Bad Type
description: A type is missing/badly implemented? Please tell us
title: "[TYPE]: <TITLE>"
labels: ["missing-types", "wrong-types"]
assignees:
  - DrKJeff16

body:
  - type: checkboxes
    attributes:
      label: Before we begin...
      description: "Make sure to read every checkbox and answer truthfully:"
      options:
        - label: I have checked for existing issues related to this one, whether open or closed
          required: true
        - label: I have checked for existing PRs and none address this, whether open or closed
          required: true
        - label: I have read the WezTerm Lua Reference and can confirm this type is not deprecated
          required: true
  - type: input
    attributes:
      label: "What version of WezTerm are you using? (`wezterm --version`)"
      placeholder: wezterm 20250725-073938-dd6e5bd2
    validations:
      required: true
  - type: input
    attributes:
      label: "What's the text editor you're using?"
      placeholder: "nvim|vscode|..."
    validations:
      required: false
  - type: input
    attributes:
      label: "Operating system and, if possible, what version?"
      placeholder: Arch Linux 6.15.6-arch1-1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the issue
      description: Write down what's wrong, as detailed as you can. Avoid irrelevant info
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Types
      description: Describe what were you expecting to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Info and/or Screenshots
      description: If there's more info you could tell, please do. Screenshots too, if applicable
    validations:
      required: false
