---@meta

---This event is triggered when the GUI is starting up after attaching the selected domain.
---For example, when you use `wezterm connect DOMAIN` or `wezterm start --domain DOMAIN`to start the GUI,
---the `gui-attached` event will be triggered and passed the `MuxDomain` object associated with `DOMAIN`.
---
---In cases where you don't specify the domain, the default domain will be passed instead.
---
---This event fires after the `gui-startup` event.
---
---Note that the `gui-startup` event does not fire when invoking `wezterm connect DOMAIN`
---or `wezterm start --domain DOMAIN --attach`
---@alias GuiAttached "gui-attached"

---The `gui-startup` event is emitted once when the GUI server is starting up when running the
---`wezterm start` subcommand.
---
---If no explicit program was passed to `wezterm start`, and if the `gui-startup` event
---causes any panes to be created then those will take precedence
---over the default program configuration
---and no additional default program will be spawned.
---
---This event is useful for starting a set of programs in a standard configuration
---to save you the effort of doing it manually each time.
---
---
--- - It is triggered before any default program is started
--- - This event fires before `gui-attached`
--- - This event does not fire for `wezterm connect` invocations
--- - The event receives an optional `SpawnCommand` argument that corresponds to
---  any arguments that may have been passed via `wezterm start`.
---  In earlier releases if you implemented this event,
---  you would essentially prevent `wezterm start -- something`
---  from spawning something.
---
---The intent is for you to use the information in the command object to spawn a new window,
---but you can choose to use or ignore it as suits your purpose
---@alias GuiStartup "gui-startup"

---@alias GuiEvent
---|GuiAttached
---|GuiStartup
