---@meta

-- The `mux-is-process-stateful` event is emitted when the multiplexer layer
-- wants to determine whether a given `Pane` can be closed
-- without prompting the user.
--
-- - This event is synchronous and must return as quickly as possible
--   in order to avoid blocking the multiplexer
-- - The event is passed a `LocalProcessInfo` object representing the process
--   that corresponds to the pane
--
-- The hook can return one of the following values:
-- - `true`: to indicate that this process tree is considered to be stateful
--         and that the user should be prompted before terminating the pane
-- - `false`: to indicate that the process tree can be terminated without prompting the user
--
-- Any other value means to use the default behavior, which is to consider the
-- `skip_close_confirmation_for_processes_named` configuration option
--
---@alias MuxProcessStateful "mux-is-process-stateful"

-- The `mux-startup` event is emitted once when the mux server is starting up.
-- It is triggered before any default program is started.
--
-- If the `mux-startup` event causes any panes to be created then
-- those will take precedence over the default program configuration
-- and no additional default program will be spawned.
--
-- This event is useful for starting a set of programs in a standard configuration
-- to save you the effort of doing it manually each time
---@alias MuxStartup "mux-startup"

---@alias MultiplexerEvent
---|MuxProcessStateful
---|MuxStartup
