---@meta

---Describes a tab.
---
---`TabInformation` is purely a snapshot of some of the
---key characteristics of the tab, intended for use in synchronous,
---fast, event callbacks that format GUI elements
---such as the window and tab title bars.
---
---@class TabInformation
---@field active_pane PaneInformation
---@field is_active boolean
---@field is_last_active boolean
---@field tab_id integer
---@field tab_index integer
---The title of the tab.
---
---@field tab_title string
---The ID of the window that contains this tab.
---
---@field window_id integer
---The title of the window that contains this tab.
---
---@field window_title string
