---@meta

--TODO:? make key and mods more specific

---@alias KeyAssignment "ActivateCommandPalette" | "ActivateCopyMode" | "ActivateKeyTable" | "ActivateLastTab" | "ActivatePaneByIndex" | "ActivatePaneDirection" | "ActivateTab" | "ActivateTabRelative" | "ActivateTabRelativeNoWrap" | "ActivateWindow" | "ActivateWindowRelative" | "ActivateWindowRelativeNoWrap" | "AdjustPaneSize" | "AttachDomain" | "CharSelect" | "ClearKeyTableStack" | "ClearScrollback" | "ClearSelection" | "CloseCurrentPane" | "CloseCurrentTab" | "CompleteSelection" | "CompleteSelectionOrOpenLinkAtMouseCursor" | "Copy" | "CopyTo" | "DecreaseFontSize" | "DetachDomain" | "DisableDefaultAssignment" | "EmitEvent" | "ExtendSelectionToMouseCursor" | "Hide" | "HideApplication" | "IncreaseFontSize" | "InputSelector" | "MoveTab" | "MoveTabRelative" | "Multiple" | "Nop" | "OpenLinkAtMouseCursor" | "PaneSelect" | "Paste" | "PasteFrom" | "PastePrimarySelection" | "PopKeyTable" | "PromptInputLine" | "QuickSelect" | "QuickSelectArgs" | "QuitApplication" | "ReloadConfiguration" | "ResetFontAndWindowSize" | "ResetFontSize" | "ResetTerminal" | "RotatePanes" | "ScrollByCurrentEventWheelDelta" | "ScrollByLine" | "ScrollByPage" | "ScrollToBottom" | "ScrollToPrompt" | "ScrollToTop" | "Search" | "SelectTextAtMouseCursor" | "SendKey" | "SendString" | "SetPaneZoomState" | "Show" | "ShowDebugOverlay" | "ShowLauncher" | "ShowLauncherArgs" | "ShowTabNavigator" | "SpawnCommandInNewTab" | "SpawnCommandInNewWindow" | "SpawnTab" | "SpawnWindow" | "SplitHorizontal" | "SplitPane" | "SplitVertical" | "StartWindowDrag" | "SwitchToWorkspace" | "SwitchWorkspaceRelative" | "ToggleFullScreen" | "TogglePaneZoomState"

---@class KeyNoAction
---@field key string
---@field mods string

---@class Key :KeyNoAction
---@field action KeyNoAction

-- ActivateCommandPalette
-- ActivateCopyMode
-- ActivateKeyTable
-- ActivateLastTab
-- ActivatePaneByIndex
-- ActivatePaneDirection
-- ActivateTab
-- ActivateTabRelative
-- ActivateTabRelativeNoWrap
-- ActivateWindow
-- ActivateWindowRelative
-- ActivateWindowRelativeNoWrap
-- AdjustPaneSize
-- AttachDomain
-- CharSelect
-- ClearKeyTableStack
-- ClearScrollback
-- ClearSelection
-- CloseCurrentPane
-- CloseCurrentTab
-- CompleteSelection
-- CompleteSelectionOrOpenLinkAtMouseCursor
-- Copy
-- CopyTo
-- DecreaseFontSize
-- DetachDomain
-- DisableDefaultAssignment
-- EmitEvent
-- ExtendSelectionToMouseCursor
-- Hide
-- HideApplication
-- IncreaseFontSize
-- InputSelector
-- MoveTab
-- MoveTabRelative
-- Multiple
-- Nop
-- OpenLinkAtMouseCursor
-- PaneSelect
-- Paste
-- PasteFrom
-- PastePrimarySelection
-- PopKeyTable
-- PromptInputLine
-- QuickSelect
-- QuickSelectArgs
-- QuitApplication
-- ReloadConfiguration
-- ResetFontAndWindowSize
-- ResetFontSize
-- ResetTerminal
-- RotatePanes
-- ScrollByCurrentEventWheelDelta
-- ScrollByLine
-- ScrollByPage
-- ScrollToBottom
-- ScrollToPrompt
-- ScrollToTop
-- Search
-- SelectTextAtMouseCursor
-- SendKey
-- SendString
-- SetPaneZoomState
-- Show
-- ShowDebugOverlay
-- ShowLauncher
-- ShowLauncherArgs
-- ShowTabNavigator
-- SpawnCommandInNewTab
-- SpawnCommandInNewWindow
-- SpawnTab
-- SpawnWindow
-- SplitHorizontal
-- SplitPane
-- SplitVertical
-- StartWindowDrag
-- SwitchToWorkspace
-- SwitchWorkspaceRelative
-- ToggleFullScreen
-- TogglePaneZoomState

---@alias ActivateCommandPalette {ActivateCommandPalette: any}
---@alias ActivateCopyMode {ActivateCopyMode: any}
---@alias ActivateKeyTable {ActivateKeyTable: any}
---@alias ActivateLastTab {ActivateLastTab: any}
---@alias ActivatePaneByIndex {ActivatePaneByIndex: any}
---@alias ActivatePaneDirection {ActivatePaneDirection: any}
---@alias ActivateTab {ActivateTab: any}
---@alias ActivateTabRelative {ActivateTabRelative: any}
---@alias ActivateTabRelativeNoWrap {ActivateTabRelativeNoWrap: any}
---@alias ActivateWindow {ActivateWindow: any}
---@alias ActivateWindowRelative {ActivateWindowRelative: any}
---@alias ActivateWindowRelativeNoWrap {ActivateWindowRelativeNoWrap: any}
---@alias AdjustPaneSize {AdjustPaneSize: any}
---@alias AttachDomain {AttachDomain: any}
---@alias CharSelect {CharSelect: any}
---@alias ClearKeyTableStack {ClearKeyTableStack: any}
---@alias ClearScrollback {ClearScrollback: any}
---@alias ClearSelection {ClearSelection: any}
---@alias CloseCurrentPane {CloseCurrentPane: any}
---@alias CloseCurrentTab {CloseCurrentTab: any}
---@alias CompleteSelection {CompleteSelection: any}
---@alias CompleteSelectionOrOpenLinkAtMouseCursor {CompleteSelectionOrOpenLinkAtMouseCursor: any}
---@alias Copy {Copy: any}
---@alias CopyTo {CopyTo: any}
---@alias DecreaseFontSize {DecreaseFontSize: any}
---@alias DetachDomain {DetachDomain: any}
---@alias DisableDefaultAssignment {DisableDefaultAssignment: any}
---@alias EmitEvent {EmitEvent: any}
---@alias ExtendSelectionToMouseCursor {ExtendSelectionToMouseCursor: any}
---@alias Hide {Hide: any}
---@alias HideApplication {HideApplication: any}
---@alias IncreaseFontSize {IncreaseFontSize: any}
---@alias InputSelector {InputSelector: any}
---@alias MoveTab {MoveTab: any}
---@alias MoveTabRelative {MoveTabRelative: any}
---@alias Multiple {Multiple: any}
---@alias Nop {Nop: any}
---@alias OpenLinkAtMouseCursor {OpenLinkAtMouseCursor: any}
---@alias PaneSelect {PaneSelect: any}
---@alias Paste {Paste: any}
---@alias PasteFrom {PasteFrom: any}
---@alias PastePrimarySelection {PastePrimarySelection: any}
---@alias PopKeyTable {PopKeyTable: any}
---@alias PromptInputLine {PromptInputLine: any}
---@alias QuickSelect {QuickSelect: any}
---@alias QuickSelectArgs {QuickSelectArgs: any}
---@alias QuitApplication {QuitApplication: any}
---@alias ReloadConfiguration {ReloadConfiguration: any}
---@alias ResetFontAndWindowSize {ResetFontAndWindowSize: any}
---@alias ResetFontSize {ResetFontSize: any}
---@alias ResetTerminal {ResetTerminal: any}
---@alias RotatePanes {RotatePanes: any}
---@alias ScrollByCurrentEventWheelDelta {ScrollByCurrentEventWheelDelta: any}
---@alias ScrollByLine {ScrollByLine: any}
---@alias ScrollByPage {ScrollByPage: any}
---@alias ScrollToBottom {ScrollToBottom: any}
---@alias ScrollToPrompt {ScrollToPrompt: any}
---@alias ScrollToTop {ScrollToTop: any}
---@alias Search {Search: any}
---@alias SelectTextAtMouseCursor {SelectTextAtMouseCursor: any}
---@alias SendKey {SendKey: any}
---@alias SendString {SendString: any}
---@alias SetPaneZoomState {SetPaneZoomState: any}
---@alias Show {Show: any}
---@alias ShowDebugOverlay {ShowDebugOverlay: any}
---@alias ShowLauncher {ShowLauncher: any}
---@alias ShowLauncherArgs {ShowLauncherArgs: any}
---@alias ShowTabNavigator {ShowTabNavigator: any}
---@alias SpawnCommandInNewTab {SpawnCommandInNewTab: any}
---@alias SpawnCommandInNewWindow {SpawnCommandInNewWindow: any}
---@alias SpawnTab {SpawnTab: any}
---@alias SpawnWindow {SpawnWindow: any}
---@alias SplitHorizontal {SplitHorizontal: any}
---@alias SplitPane {SplitPane: any}
---@alias SplitVertical {SplitVertical: any}
---@alias StartWindowDrag {StartWindowDrag: any}
---@alias SwitchToWorkspace {SwitchToWorkspace: any}
---@alias SwitchWorkspaceRelative {SwitchWorkspaceRelative: any}
---@alias ToggleFullScreen {ToggleFullScreen: any}
---@alias TogglePaneZoomState {TogglePaneZoomState: any}

---@alias KeyAssignmentTables ActivateCommandPalette | ActivateCopyMode | ActivateKeyTable | ActivateLastTab | ActivatePaneByIndex | ActivatePaneDirection | ActivateTab | ActivateTabRelative | ActivateTabRelativeNoWrap | ActivateWindow | ActivateWindowRelative | ActivateWindowRelativeNoWrap | AdjustPaneSize | AttachDomain | CharSelect | ClearKeyTableStack | ClearScrollback | ClearSelection | CloseCurrentPane | CloseCurrentTab | CompleteSelection | CompleteSelectionOrOpenLinkAtMouseCursor | Copy | CopyTo | DecreaseFontSize | DetachDomain | DisableDefaultAssignment | EmitEvent | ExtendSelectionToMouseCursor | Hide | HideApplication | IncreaseFontSize | InputSelector | MoveTab | MoveTabRelative | Multiple | Nop | OpenLinkAtMouseCursor | PaneSelect | Paste | PasteFrom | PastePrimarySelection | PopKeyTable | PromptInputLine | QuickSelect | QuickSelectArgs | QuitApplication | ReloadConfiguration | ResetFontAndWindowSize | ResetFontSize | ResetTerminal | RotatePanes | ScrollByCurrentEventWheelDelta | ScrollByLine | ScrollByPage | ScrollToBottom | ScrollToPrompt | ScrollToTop | Search | SelectTextAtMouseCursor | SendKey | SendString | SetPaneZoomState | Show | ShowDebugOverlay | ShowLauncher | ShowLauncherArgs | ShowTabNavigator | SpawnCommandInNewTab | SpawnCommandInNewWindow | SpawnTab | SpawnWindow | SplitHorizontal | SplitPane | SplitVertical | StartWindowDrag | SwitchToWorkspace | SwitchWorkspaceRelative | ToggleFullScreen | TogglePaneZoomState
